- hosts: all
  become: true
  tasks:
    - name: install apache package
      yum:
        name: httpd
        state: present
    - name: start and enable webserver
      service:
        name: httpd
        state: started
        enabled: true
    - name: restart the server
      service: 
        name: httpd
        state: restarted
        enabled: true
    - name: insert index file
      template: 
        src: index.html
        dest: /var/www/html/index.html

