- hosts: all
  become: true
  tasks:
    - name: install docker
      yum:
        name: docker
        state: present
    - name: start and present dcoker
      service:
        name: docker
        state: started
        enabled: true

